### PR TITLE
Node and swift

### PR DESCRIPTION
**Pull request by vincentjames501**
I haven't looked into this, but Chrome appears to be WAY faster than node for this...

### CODE REVIEW

**Comment by jamesmunns** [comment]
1.8-2.0 seconds for Node, 470-485ms for swift, not sure how to test browser, but I assume its not far off :)

**Comment by vincentjames501** [comment]
Just paste the code into the developer JavaScript console in Chrome.

**Comment by vincentjames501** [comment]
You should probably put what versions of Swift, Node, Java, etc as well as that can have a lot to do with it.

**Comment by vincentjames501** [comment]
Oh, FWIW, swift's enumerate() method (like in Python) was ridiculously slow (like 4x slower). Maybe Python could be faster with a more raw for/while loop?

**Comment by jamesmunns** [comment]
True. I'll open an issue. I generally have been installing most of these tools (other than C/Rust/Python), so they are whatever is current in Homebrew, but should document.

browser was 680-850ms, btw

**Comment by jamesmunns** [comment]
https://github.com/jamesmunns/rust-linking/issues/5#issuecomment-242918241

I'll add it to the markdown later. @vincentjames501 feel free to hack on any of the other languages if you like to get the speeds up, if it starts looking less idiomatic, we can break it out.

**Pull request merged**
