### PR TITLE
Add clojure

### PR DESCRIPTION
**Pull request by vincentjames501**

### CODE REVIEW

**Comment by jamesmunns** [comment]
@vincentjames501 please change the timing to "55-70ms" and I will merge (based on my very scientific reference machine :D

```
"Elapsed time: 71.0767 msecs"
"Elapsed time: 65.18166 msecs"
"Elapsed time: 59.569136 msecs"
"Elapsed time: 65.576669 msecs"
"Elapsed time: 66.423012 msecs"
"Elapsed time: 64.738601 msecs"
"Elapsed time: 66.917719 msecs"
"Elapsed time: 63.400707 msecs"
"Elapsed time: 61.070243 msecs"
"Elapsed time: 59.17844 msecs"
"Elapsed time: 59.983026 msecs"
"Elapsed time: 59.539165 msecs"
"Elapsed time: 63.636295 msecs"
"Elapsed time: 57.500165 msecs"
"Elapsed time: 54.994122 msecs"
```

**Comment by jamesmunns** [comment]
Also thanks!

**Comment by vincentjames501** [comment]
Cheers :). Boy, Clojure is a lot more ugly when you have to deal with Java primitives!

**Comment by jamesmunns** [comment]
👍

**Pull request merged**
